// Bygger PR-beskrivningen för nightly-jobbets auto-PR (2026-09-23).
//
// Läser output/youtube-autofix-report.json (skriven av youtube/autofix.ts
// --apply) och skriver output/clip-fix-pr.md: en tabell per bytt klipp med
// klickbar YouTube-länk så Peter kan validera på telefonen (= riktig
// uppspelning från Sverige, den enda test som ser region-/claim-block),
// plus en lista över klipp som INTE kunde ersättas automatiskt.
//
// Varningsflaggor per kandidat:
//   ⚠ kanal  — inte VEVO / "- Topic" / uppenbar officiell kanal (re-uploads
//             är de som claim-blockas per land)
//   ⚠ år     — videotiteln innehåller ett 4-siffrigt år (spoilar "Which year?")
//
// Skriver också antalet applicerade byten till GITHUB_OUTPUT (applied=N) så
// workflowet kan hoppa över PR:en när inget ändrats.
//
// Kör: cd backend && npx tsx scripts/clip-fix-pr-body.ts

import * as fs from 'fs';
import * as path from 'path';

interface Replacement {
  videoId: string;
  title: string;
  channelTitle: string;
  score: number;
  blockReasons: string[];
}
interface Entry {
  filename: string;
  itemId: string;
  displayName: string;
  oldVideoId: string;
  status: 'broken' | 'missing';
  reasons: string[];
  replacement: Replacement | null;
  applied: boolean;
}

const OUT_DIR = path.join(process.cwd(), 'output');
const REPORT = path.join(OUT_DIR, 'youtube-autofix-report.json');
const PR_BODY = path.join(OUT_DIR, 'clip-fix-pr.md');

const OFFICIAL_CHANNEL = /vevo|- topic$|official|records|recordings|music group|entertainment$/i;
const YEAR_IN_TITLE = /\b(19[0-9]{2}|20[0-9]{2})\b/;

function esc(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function main(): void {
  const entries: Entry[] = fs.existsSync(REPORT)
    ? (JSON.parse(fs.readFileSync(REPORT, 'utf-8')) as Entry[])
    : [];
  const applied = entries.filter((e) => e.applied && e.replacement);
  const unfixed = entries.filter((e) => !e.applied);

  const lines: string[] = [
    'Nightly found YouTube clips that no longer play. This PR swaps them for the best-scoring replacement.',
    '',
    '**How to check (on your phone, in Sweden):** open each new link and confirm',
    '1. it plays,',
    '2. it is the right song / film / event,',
    '3. the video title does not give away the year.',
    '',
    'Wrong pick? Comment on the PR with the right link, or ask Claude to fix the PR.',
    'Merging publishes the change to phones as an OTA update.',
    '',
  ];

  if (applied.length) {
    lines.push(
      `## Replaced (${applied.length})`,
      '',
      '| Item | Old clip | New clip | Channel | Flags |',
      '|---|---|---|---|---|',
    );
    for (const e of applied) {
      const r = e.replacement!;
      const flags: string[] = [];
      if (!OFFICIAL_CHANNEL.test(r.channelTitle)) flags.push('⚠ unofficial channel');
      if (YEAR_IN_TITLE.test(r.title)) flags.push('⚠ year in title');
      if (r.blockReasons.length) flags.push(`⚠ ${r.blockReasons.join(', ')}`);
      lines.push(
        `| **${esc(e.displayName)}**<br>\`${e.itemId}\` | \`${e.oldVideoId}\` — ${esc(
          e.reasons.join(', '),
        )} | [${esc(r.title)}](https://www.youtube.com/watch?v=${r.videoId}) | ${esc(
          r.channelTitle,
        )} | ${flags.join('<br>') || '✓'} |`,
      );
    }
    lines.push('');
  }

  if (unfixed.length) {
    lines.push(
      `## Could not be replaced automatically (${unfixed.length})`,
      '',
      'Needs a manual pick (no candidate scored high enough). These items stay broken until fixed:',
      '',
    );
    for (const e of unfixed) {
      lines.push(`- **${e.displayName}** (\`${e.itemId}\`, ${e.filename}) — \`${e.oldVideoId}\`: ${e.reasons.join(', ')}`);
    }
    lines.push('');
  }

  lines.push('_Generated by `youtube-validate-nightly`._');

  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(PR_BODY, lines.join('\n'), 'utf-8');
  console.log(`applied=${applied.length} unfixed=${unfixed.length} → ${PR_BODY}`);
  const ghOut = process.env.GITHUB_OUTPUT;
  if (ghOut) {
    fs.appendFileSync(ghOut, `applied=${applied.length}\nunfixed=${unfixed.length}\n`);
  }
}

main();
