// Auto-generatable bild-katalog för quiz-frågor.
// require()-statements måste vara statiska i Metro/RN, så vi kan inte loop:a
// över filenames runtime — varje bild måste explicit listas här.
//
// När backend processar fler items: kopiera webp till assets/quiz-images/
// och lägg till en rad i QUIZ_IMAGES nedan.

import type { ImageSourcePropType } from 'react-native';

export const QUIZ_IMAGES: Record<string, ImageSourcePropType> = {
  'abba': require('../../assets/quiz-images/abba.webp'),
  'acdc': require('../../assets/quiz-images/acdc.webp'),
  'adele': require('../../assets/quiz-images/adele.webp'),
  'aerosmith': require('../../assets/quiz-images/aerosmith.webp'),
  'arctic-monkeys': require('../../assets/quiz-images/arctic-monkeys.webp'),
  'armand-duplantis': require('../../assets/quiz-images/armand-duplantis.webp'),
  'arnold-schwarzenegger': require('../../assets/quiz-images/arnold-schwarzenegger.webp'),
  'audrey-hepburn': require('../../assets/quiz-images/audrey-hepburn.webp'),
  'avicii': require('../../assets/quiz-images/avicii.webp'),
  'bad-bunny': require('../../assets/quiz-images/bad-bunny.webp'),
  'beatles': require('../../assets/quiz-images/beatles.webp'),
  'bjorn-borg': require('../../assets/quiz-images/bjorn-borg.webp'),
  'black-sabbath': require('../../assets/quiz-images/black-sabbath.webp'),
  'bob-dylan': require('../../assets/quiz-images/bob-dylan.webp'),
  'boris-becker': require('../../assets/quiz-images/boris-becker.webp'),
  'brad-pitt': require('../../assets/quiz-images/brad-pitt.webp'),
  'bruce-springsteen': require('../../assets/quiz-images/bruce-springsteen.webp'),
  'bruno-mars': require('../../assets/quiz-images/bruno-mars.webp'),
  'carl-lewis': require('../../assets/quiz-images/carl-lewis.webp'),
  'cary-grant': require('../../assets/quiz-images/cary-grant.webp'),
  'cher': require('../../assets/quiz-images/cher.webp'),
  'coldplay': require('../../assets/quiz-images/coldplay.webp'),
  'cristiano-ronaldo': require('../../assets/quiz-images/cristiano-ronaldo.webp'),
  'david-bowie': require('../../assets/quiz-images/david-bowie.webp'),
  'diego-maradona': require('../../assets/quiz-images/diego-maradona.webp'),
  'dua-lipa': require('../../assets/quiz-images/dua-lipa.webp'),
  'eagles': require('../../assets/quiz-images/eagles.webp'),
  'ed-sheeran': require('../../assets/quiz-images/ed-sheeran.webp'),
  'elvis-presley': require('../../assets/quiz-images/elvis-presley.webp'),
  'emma-stone': require('../../assets/quiz-images/emma-stone.webp'),
  'fleetwood-mac': require('../../assets/quiz-images/fleetwood-mac.webp'),
  'florence-pugh': require('../../assets/quiz-images/florence-pugh.webp'),
  'foo-fighters': require('../../assets/quiz-images/foo-fighters.webp'),
  'frank-sinatra': require('../../assets/quiz-images/frank-sinatra.webp'),
  'guns-n-roses': require('../../assets/quiz-images/guns-n-roses.webp'),
  'ingrid-bergman': require('../../assets/quiz-images/ingrid-bergman.webp'),
  'james-brown': require('../../assets/quiz-images/james-brown.webp'),
  'jenna-ortega': require('../../assets/quiz-images/jenna-ortega.webp'),
  'jennifer-aniston': require('../../assets/quiz-images/jennifer-aniston.webp'),
  'julia-roberts': require('../../assets/quiz-images/julia-roberts.webp'),
  'justin-timberlake': require('../../assets/quiz-images/justin-timberlake.webp'),
  'katharine-hepburn': require('../../assets/quiz-images/katharine-hepburn.webp'),
  'lady-gaga': require('../../assets/quiz-images/lady-gaga.webp'),
  'larry-bird': require('../../assets/quiz-images/larry-bird.webp'),
  'lasse-aberg': require('../../assets/quiz-images/lasse-aberg.webp'),
  'lebron-james': require('../../assets/quiz-images/lebron-james.webp'),
  'led-zeppelin': require('../../assets/quiz-images/led-zeppelin.webp'),
  'leonardo-dicaprio': require('../../assets/quiz-images/leonardo-dicaprio.webp'),
  'lewis-hamilton': require('../../assets/quiz-images/lewis-hamilton.webp'),
  'lionel-messi': require('../../assets/quiz-images/lionel-messi.webp'),
  'louis-armstrong': require('../../assets/quiz-images/louis-armstrong.webp'),
  'madonna': require('../../assets/quiz-images/madonna.webp'),
  'magic-johnson': require('../../assets/quiz-images/magic-johnson.webp'),
  'margot-robbie': require('../../assets/quiz-images/margot-robbie.webp'),
  'marilyn-monroe': require('../../assets/quiz-images/marilyn-monroe.webp'),
  'mark-spitz': require('../../assets/quiz-images/mark-spitz.webp'),
  'martina-navratilova': require('../../assets/quiz-images/martina-navratilova.webp'),
  'meryl-streep': require('../../assets/quiz-images/meryl-streep.webp'),
  'metallica': require('../../assets/quiz-images/metallica.webp'),
  'michael-jackson': require('../../assets/quiz-images/michael-jackson.webp'),
  'michael-jordan': require('../../assets/quiz-images/michael-jordan.webp'),
  'mike-tyson': require('../../assets/quiz-images/mike-tyson.webp'),
  'millie-bobby-brown': require('../../assets/quiz-images/millie-bobby-brown.webp'),
  'muhammad-ali': require('../../assets/quiz-images/muhammad-ali.webp'),
  'naomi-osaka': require('../../assets/quiz-images/naomi-osaka.webp'),
  'nat-king-cole': require('../../assets/quiz-images/nat-king-cole.webp'),
  'nirvana': require('../../assets/quiz-images/nirvana.webp'),
  'olivia-rodrigo': require('../../assets/quiz-images/olivia-rodrigo.webp'),
  'pele': require('../../assets/quiz-images/pele.webp'),
  'peter-forsberg': require('../../assets/quiz-images/peter-forsberg.webp'),
  'pink': require('../../assets/quiz-images/pink.webp'),
  'pink-floyd': require('../../assets/quiz-images/pink-floyd.webp'),
  'prince': require('../../assets/quiz-images/prince.webp'),
  'queen': require('../../assets/quiz-images/queen.webp'),
  'ray-charles': require('../../assets/quiz-images/ray-charles.webp'),
  'robert-de-niro': require('../../assets/quiz-images/robert-de-niro.webp'),
  'robin-williams': require('../../assets/quiz-images/robin-williams.webp'),
  'roger-federer': require('../../assets/quiz-images/roger-federer.webp'),
  'rolling-stones': require('../../assets/quiz-images/rolling-stones.webp'),
  'sean-connery': require('../../assets/quiz-images/sean-connery.webp'),
  'serena-williams': require('../../assets/quiz-images/serena-williams.webp'),
  'simone-biles': require('../../assets/quiz-images/simone-biles.webp'),
  'steffi-graf': require('../../assets/quiz-images/steffi-graf.webp'),
  'stephen-curry': require('../../assets/quiz-images/stephen-curry.webp'),
  'stevie-wonder': require('../../assets/quiz-images/stevie-wonder.webp'),
  'taylor-swift': require('../../assets/quiz-images/taylor-swift.webp'),
  'the-doors': require('../../assets/quiz-images/the-doors.webp'),
  'the-weeknd': require('../../assets/quiz-images/the-weeknd.webp'),
  'the-who': require('../../assets/quiz-images/the-who.webp'),
  'tiger-woods': require('../../assets/quiz-images/tiger-woods.webp'),
  'timothee-chalamet': require('../../assets/quiz-images/timothee-chalamet.webp'),
  'tom-brady': require('../../assets/quiz-images/tom-brady.webp'),
  'tom-cruise': require('../../assets/quiz-images/tom-cruise.webp'),
  'tom-hanks': require('../../assets/quiz-images/tom-hanks.webp'),
  'tom-holland': require('../../assets/quiz-images/tom-holland.webp'),
  'u2': require('../../assets/quiz-images/u2.webp'),
  'usain-bolt': require('../../assets/quiz-images/usain-bolt.webp'),
  'wayne-gretzky': require('../../assets/quiz-images/wayne-gretzky.webp'),
  'whitney-houston': require('../../assets/quiz-images/whitney-houston.webp'),
  'will-smith': require('../../assets/quiz-images/will-smith.webp'),
  'zendaya': require('../../assets/quiz-images/zendaya.webp'),
  'zlatan-ibrahimovic': require('../../assets/quiz-images/zlatan-ibrahimovic.webp'),
};

/** Lista över alla item-id:n som har en lokal bild tillgänglig. */
export const QUIZ_IMAGE_IDS = Object.keys(QUIZ_IMAGES);

/** Säker lookup — returnerar null om id saknar bild. */
export function getQuizImage(itemId: string): ImageSourcePropType | null {
  return QUIZ_IMAGES[itemId] ?? null;
}
