// Auto-generatable bild-katalog för quiz-frågor.
// require()-statements måste vara statiska i Metro/RN, så vi kan inte loop:a
// över filenames runtime — varje bild måste explicit listas här.
//
// Auto-genererad av backend/scripts/sync-quiz-images.ts.
// När du processar nya items via batch-wikimedia-process, kör sedan
// `tsx scripts/sync-quiz-images.ts` så uppdateras detta map automatiskt.

import type { ImageSourcePropType } from 'react-native';

export const QUIZ_IMAGES: Record<string, ImageSourcePropType> = {
  'abba': require('../../assets/quiz-images/abba.webp'),
  'acdc': require('../../assets/quiz-images/acdc.webp'),
  'adam-sandler': require('../../assets/quiz-images/adam-sandler.webp'),
  'adele': require('../../assets/quiz-images/adele.webp'),
  'aerosmith': require('../../assets/quiz-images/aerosmith.webp'),
  'al-pacino': require('../../assets/quiz-images/al-pacino.webp'),
  'andrew-garfield': require('../../assets/quiz-images/andrew-garfield.webp'),
  'annika-sorenstam': require('../../assets/quiz-images/annika-sorenstam.webp'),
  'anthony-hopkins': require('../../assets/quiz-images/anthony-hopkins.webp'),
  'anya-taylor-joy': require('../../assets/quiz-images/anya-taylor-joy.webp'),
  'arctic-monkeys': require('../../assets/quiz-images/arctic-monkeys.webp'),
  'armand-duplantis': require('../../assets/quiz-images/armand-duplantis.webp'),
  'arnold-schwarzenegger': require('../../assets/quiz-images/arnold-schwarzenegger.webp'),
  'audrey-hepburn': require('../../assets/quiz-images/audrey-hepburn.webp'),
  'avicii': require('../../assets/quiz-images/avicii.webp'),
  'bad-bunny': require('../../assets/quiz-images/bad-bunny.webp'),
  'beatles': require('../../assets/quiz-images/beatles.webp'),
  'ben-affleck': require('../../assets/quiz-images/ben-affleck.webp'),
  'bette-davis': require('../../assets/quiz-images/bette-davis.webp'),
  'bjorn-borg': require('../../assets/quiz-images/bjorn-borg.webp'),
  'black-sabbath': require('../../assets/quiz-images/black-sabbath.webp'),
  'bob-dylan': require('../../assets/quiz-images/bob-dylan.webp'),
  'boris-becker': require('../../assets/quiz-images/boris-becker.webp'),
  'brad-pitt': require('../../assets/quiz-images/brad-pitt.webp'),
  'bruce-springsteen': require('../../assets/quiz-images/bruce-springsteen.webp'),
  'bruce-willis': require('../../assets/quiz-images/bruce-willis.webp'),
  'bruno-mars': require('../../assets/quiz-images/bruno-mars.webp'),
  'carl-lewis': require('../../assets/quiz-images/carl-lewis.webp'),
  'cary-grant': require('../../assets/quiz-images/cary-grant.webp'),
  'cate-blanchett': require('../../assets/quiz-images/cate-blanchett.webp'),
  'charlie-chaplin': require('../../assets/quiz-images/charlie-chaplin.webp'),
  'charlize-theron': require('../../assets/quiz-images/charlize-theron.webp'),
  'charlotte-kalla': require('../../assets/quiz-images/charlotte-kalla.webp'),
  'cher': require('../../assets/quiz-images/cher.webp'),
  'christian-bale': require('../../assets/quiz-images/christian-bale.webp'),
  'clark-gable': require('../../assets/quiz-images/clark-gable.webp'),
  'coldplay': require('../../assets/quiz-images/coldplay.webp'),
  'cristiano-ronaldo': require('../../assets/quiz-images/cristiano-ronaldo.webp'),
  'daniel-radcliffe': require('../../assets/quiz-images/daniel-radcliffe.webp'),
  'david-bowie': require('../../assets/quiz-images/david-bowie.webp'),
  'denzel-washington': require('../../assets/quiz-images/denzel-washington.webp'),
  'diane-keaton': require('../../assets/quiz-images/diane-keaton.webp'),
  'diego-maradona': require('../../assets/quiz-images/diego-maradona.webp'),
  'dua-lipa': require('../../assets/quiz-images/dua-lipa.webp'),
  'dustin-hoffman': require('../../assets/quiz-images/dustin-hoffman.webp'),
  'eagles': require('../../assets/quiz-images/eagles.webp'),
  'ed-sheeran': require('../../assets/quiz-images/ed-sheeran.webp'),
  'eddie-murphy': require('../../assets/quiz-images/eddie-murphy.webp'),
  'elvis-presley': require('../../assets/quiz-images/elvis-presley.webp'),
  'emma-stone': require('../../assets/quiz-images/emma-stone.webp'),
  'emma-watson': require('../../assets/quiz-images/emma-watson.webp'),
  'erling-haaland': require('../../assets/quiz-images/erling-haaland.webp'),
  'finn-wolfhard': require('../../assets/quiz-images/finn-wolfhard.webp'),
  'fleetwood-mac': require('../../assets/quiz-images/fleetwood-mac.webp'),
  'florence-pugh': require('../../assets/quiz-images/florence-pugh.webp'),
  'foo-fighters': require('../../assets/quiz-images/foo-fighters.webp'),
  'frank-sinatra': require('../../assets/quiz-images/frank-sinatra.webp'),
  'gary-cooper': require('../../assets/quiz-images/gary-cooper.webp'),
  'gene-hackman': require('../../assets/quiz-images/gene-hackman.webp'),
  'goldie-hawn': require('../../assets/quiz-images/goldie-hawn.webp'),
  'green-day': require('../../assets/quiz-images/green-day.webp'),
  'gregory-peck': require('../../assets/quiz-images/gregory-peck.webp'),
  'guns-n-roses': require('../../assets/quiz-images/guns-n-roses.webp'),
  'harry-styles': require('../../assets/quiz-images/harry-styles.webp'),
  'helena-bonham-carter': require('../../assets/quiz-images/helena-bonham-carter.webp'),
  'henrik-stenson': require('../../assets/quiz-images/henrik-stenson.webp'),
  'hugh-jackman': require('../../assets/quiz-images/hugh-jackman.webp'),
  'humphrey-bogart': require('../../assets/quiz-images/humphrey-bogart.webp'),
  'imagine-dragons': require('../../assets/quiz-images/imagine-dragons.webp'),
  'ingrid-bergman': require('../../assets/quiz-images/ingrid-bergman.webp'),
  'jack-nicholson': require('../../assets/quiz-images/jack-nicholson.webp'),
  'jack-nicklaus': require('../../assets/quiz-images/jack-nicklaus.webp'),
  'jacob-elordi': require('../../assets/quiz-images/jacob-elordi.webp'),
  'jake-gyllenhaal': require('../../assets/quiz-images/jake-gyllenhaal.webp'),
  'james-brown': require('../../assets/quiz-images/james-brown.webp'),
  'james-dean': require('../../assets/quiz-images/james-dean.webp'),
  'james-stewart': require('../../assets/quiz-images/james-stewart.webp'),
  'jeff-bridges': require('../../assets/quiz-images/jeff-bridges.webp'),
  'jenna-ortega': require('../../assets/quiz-images/jenna-ortega.webp'),
  'jennifer-aniston': require('../../assets/quiz-images/jennifer-aniston.webp'),
  'jim-carrey': require('../../assets/quiz-images/jim-carrey.webp'),
  'joe-montana': require('../../assets/quiz-images/joe-montana.webp'),
  'john-mcenroe': require('../../assets/quiz-images/john-mcenroe.webp'),
  'johnny-depp': require('../../assets/quiz-images/johnny-depp.webp'),
  'jude-law': require('../../assets/quiz-images/jude-law.webp'),
  'julia-roberts': require('../../assets/quiz-images/julia-roberts.webp'),
  'justin-timberlake': require('../../assets/quiz-images/justin-timberlake.webp'),
  'kate-winslet': require('../../assets/quiz-images/kate-winslet.webp'),
  'katharine-hepburn': require('../../assets/quiz-images/katharine-hepburn.webp'),
  'kobe-bryant': require('../../assets/quiz-images/kobe-bryant.webp'),
  'kristen-stewart': require('../../assets/quiz-images/kristen-stewart.webp'),
  'kylian-mbappe': require('../../assets/quiz-images/kylian-mbappe.webp'),
  'lady-gaga': require('../../assets/quiz-images/lady-gaga.webp'),
  'larry-bird': require('../../assets/quiz-images/larry-bird.webp'),
  'lasse-aberg': require('../../assets/quiz-images/lasse-aberg.webp'),
  'lebron-james': require('../../assets/quiz-images/lebron-james.webp'),
  'led-zeppelin': require('../../assets/quiz-images/led-zeppelin.webp'),
  'leonardo-dicaprio': require('../../assets/quiz-images/leonardo-dicaprio.webp'),
  'lewis-hamilton': require('../../assets/quiz-images/lewis-hamilton.webp'),
  'liam-neeson': require('../../assets/quiz-images/liam-neeson.webp'),
  'linkin-park': require('../../assets/quiz-images/linkin-park.webp'),
  'lionel-messi': require('../../assets/quiz-images/lionel-messi.webp'),
  'loreen': require('../../assets/quiz-images/loreen.webp'),
  'louis-armstrong': require('../../assets/quiz-images/louis-armstrong.webp'),
  'madonna': require('../../assets/quiz-images/madonna.webp'),
  'magic-johnson': require('../../assets/quiz-images/magic-johnson.webp'),
  'margot-robbie': require('../../assets/quiz-images/margot-robbie.webp'),
  'mariah-carey': require('../../assets/quiz-images/mariah-carey.webp'),
  'marilyn-monroe': require('../../assets/quiz-images/marilyn-monroe.webp'),
  'mark-spitz': require('../../assets/quiz-images/mark-spitz.webp'),
  'martina-navratilova': require('../../assets/quiz-images/martina-navratilova.webp'),
  'mats-wilander': require('../../assets/quiz-images/mats-wilander.webp'),
  'matt-damon': require('../../assets/quiz-images/matt-damon.webp'),
  'meryl-streep': require('../../assets/quiz-images/meryl-streep.webp'),
  'metallica': require('../../assets/quiz-images/metallica.webp'),
  'michael-jackson': require('../../assets/quiz-images/michael-jackson.webp'),
  'michael-jordan': require('../../assets/quiz-images/michael-jordan.webp'),
  'millie-bobby-brown': require('../../assets/quiz-images/millie-bobby-brown.webp'),
  'mo-salah': require('../../assets/quiz-images/mo-salah.webp'),
  'muhammad-ali': require('../../assets/quiz-images/muhammad-ali.webp'),
  'naomi-osaka': require('../../assets/quiz-images/naomi-osaka.webp'),
  'nat-king-cole': require('../../assets/quiz-images/nat-king-cole.webp'),
  'nicole-kidman': require('../../assets/quiz-images/nicole-kidman.webp'),
  'nirvana': require('../../assets/quiz-images/nirvana.webp'),
  'noah-schnapp': require('../../assets/quiz-images/noah-schnapp.webp'),
  'novak-djokovic': require('../../assets/quiz-images/novak-djokovic.webp'),
  'olivia-rodrigo': require('../../assets/quiz-images/olivia-rodrigo.webp'),
  'paul-newman': require('../../assets/quiz-images/paul-newman.webp'),
  'pele': require('../../assets/quiz-images/pele.webp'),
  'penelope-cruz': require('../../assets/quiz-images/penelope-cruz.webp'),
  'peter-forsberg': require('../../assets/quiz-images/peter-forsberg.webp'),
  'pink': require('../../assets/quiz-images/pink.webp'),
  'pink-floyd': require('../../assets/quiz-images/pink-floyd.webp'),
  'post-malone': require('../../assets/quiz-images/post-malone.webp'),
  'prince': require('../../assets/quiz-images/prince.webp'),
  'queen': require('../../assets/quiz-images/queen.webp'),
  'rafael-nadal': require('../../assets/quiz-images/rafael-nadal.webp'),
  'ray-charles': require('../../assets/quiz-images/ray-charles.webp'),
  'red-hot-chili-peppers': require('../../assets/quiz-images/red-hot-chili-peppers.webp'),
  'reese-witherspoon': require('../../assets/quiz-images/reese-witherspoon.webp'),
  'robert-de-niro': require('../../assets/quiz-images/robert-de-niro.webp'),
  'robert-downey-jr': require('../../assets/quiz-images/robert-downey-jr.webp'),
  'robert-pattinson': require('../../assets/quiz-images/robert-pattinson.webp'),
  'robert-redford': require('../../assets/quiz-images/robert-redford.webp'),
  'robin-williams': require('../../assets/quiz-images/robin-williams.webp'),
  'robyn': require('../../assets/quiz-images/robyn.webp'),
  'roger-federer': require('../../assets/quiz-images/roger-federer.webp'),
  'rolling-stones': require('../../assets/quiz-images/rolling-stones.webp'),
  'ryan-gosling': require('../../assets/quiz-images/ryan-gosling.webp'),
  'ryan-reynolds': require('../../assets/quiz-images/ryan-reynolds.webp'),
  'sadie-sink': require('../../assets/quiz-images/sadie-sink.webp'),
  'samuel-l-jackson': require('../../assets/quiz-images/samuel-l-jackson.webp'),
  'sandra-bullock': require('../../assets/quiz-images/sandra-bullock.webp'),
  'saoirse-ronan': require('../../assets/quiz-images/saoirse-ronan.webp'),
  'sean-connery': require('../../assets/quiz-images/sean-connery.webp'),
  'serena-williams': require('../../assets/quiz-images/serena-williams.webp'),
  'sigourney-weaver': require('../../assets/quiz-images/sigourney-weaver.webp'),
  'simone-biles': require('../../assets/quiz-images/simone-biles.webp'),
  'spencer-tracy': require('../../assets/quiz-images/spencer-tracy.webp'),
  'stefan-edberg': require('../../assets/quiz-images/stefan-edberg.webp'),
  'steffi-graf': require('../../assets/quiz-images/steffi-graf.webp'),
  'stephen-curry': require('../../assets/quiz-images/stephen-curry.webp'),
  'stevie-wonder': require('../../assets/quiz-images/stevie-wonder.webp'),
  'susan-sarandon': require('../../assets/quiz-images/susan-sarandon.webp'),
  'sydney-sweeney': require('../../assets/quiz-images/sydney-sweeney.webp'),
  'taylor-swift': require('../../assets/quiz-images/taylor-swift.webp'),
  'the-doors': require('../../assets/quiz-images/the-doors.webp'),
  'the-weeknd': require('../../assets/quiz-images/the-weeknd.webp'),
  'the-who': require('../../assets/quiz-images/the-who.webp'),
  'timothee-chalamet': require('../../assets/quiz-images/timothee-chalamet.webp'),
  'tina-turner': require('../../assets/quiz-images/tina-turner.webp'),
  'tom-brady': require('../../assets/quiz-images/tom-brady.webp'),
  'tom-cruise': require('../../assets/quiz-images/tom-cruise.webp'),
  'tom-hanks': require('../../assets/quiz-images/tom-hanks.webp'),
  'tom-holland': require('../../assets/quiz-images/tom-holland.webp'),
  'tom-selleck': require('../../assets/quiz-images/tom-selleck.webp'),
  'u2': require('../../assets/quiz-images/u2.webp'),
  'usain-bolt': require('../../assets/quiz-images/usain-bolt.webp'),
  'vivien-leigh': require('../../assets/quiz-images/vivien-leigh.webp'),
  'wayne-gretzky': require('../../assets/quiz-images/wayne-gretzky.webp'),
  'whitney-houston': require('../../assets/quiz-images/whitney-houston.webp'),
  'whoopi-goldberg': require('../../assets/quiz-images/whoopi-goldberg.webp'),
  'will-ferrell': require('../../assets/quiz-images/will-ferrell.webp'),
  'will-smith': require('../../assets/quiz-images/will-smith.webp'),
  'zendaya': require('../../assets/quiz-images/zendaya.webp'),
  'zlatan-ibrahimovic': require('../../assets/quiz-images/zlatan-ibrahimovic.webp'),
};

/** Lista över alla item-id:n som har en lokal bild tillgänglig. */
export const QUIZ_IMAGE_IDS = Object.keys(QUIZ_IMAGES);

/** Säker lookup — returnerar null om id saknar bild. */
export function getQuizImage(itemId: string): ImageSourcePropType | null {
  return QUIZ_IMAGES[itemId] ?? null;
}
